### ISSUE TITLE
Removing items after disabling package

### ISSUE THREAD

**Issue by suda** [suda/toolbar#1]
When package which added buttons is disabled, buttons are still shown.

This may be achieved by adding `onDidEnablePackage` and `onDidDisablePackage` in [Event Subscription](https://github.com/atom/atom/blob/v0.138.0/src/package-manager.coffee#L48) section.

**Comment by jerone** [comment]
This is not implemented out of the box, but requires a small addition in your main coffee file of the following API:
```
  deactivate: ->
    @toolBar?.removeItems()
```
