### ISSUE TITLE
Tooltip triangle is not aligned properly when on left/right

### ISSUE THREAD

**Issue by suda** [suda/toolbar#28]
![](http://cl.ly/image/2k2d3G0N2I1w/Screenshot-2015-04-21-16.35.01.png)

**Comment by jerone** [comment]
Confirmed on the right too. I could swear I have seen it working correctly.

I didn't report or tried fixing it, because I thought it was something related to Atom as sometimes I have the same issue with tooltips on tabs too. Maybe forward it to the corresponding package, anyone knows which?

**Comment by suda** [comment]
Ok, it's an [Atom issue](https://github.com/atom/atom/issues/5009). Should be fixed soon.

**Comment by jerone** [comment]
Subscribed. Thanks.

**Comment by jerone** [comment]
Just to let you know that this issue has been resolved in Atom 0.201.0 by https://github.com/atom/atom/pull/6848

**Comment by suda** [comment]
Works! Awesome :)
